

<!-- Image Map Generated by http://www.image-map.net/ -->
<img src="assets/img/erp_system.png" usemap="#image-map">

<map name="image-map">
    <area href="supplier.php" alt="Supply" title="Supply" href="" coords="62,258,308,381" shape="rect">
    <area href="item.php" alt="Inventory" title="Inventory" href="" coords="1019,210,703,93" shape="rect">
    <area href="po_list.php" alt="Purchase Orders" title="Purchase Orders" href="" coords="703,391,383,333" shape="0">
    <area target="" alt="Manufacturinga and Assembly" title="Manufacturinga and Assembly" href="" coords="983,562,1237,676" shape="0">
    <area target="" alt="Sales" title="Sales" href="" coords="1372,259,1577,381" shape="0">
    <area target="" alt="Work Orders" title="Work Orders" href="" coords="897,440,1144,508" shape="0">
    <area target="" alt="Sales Orders" title="Sales Orders" href="" coords="1014,251,1265,317,1301,490" shape="0">
</map>